// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 9e20558cde0de91135b05bd03205628f1a1e07102836547f4c60a9357d72d565

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "keycloakify-starter";

export const themeNames: ThemeName[] = ["keycloakify-starter"];

export type KcEnvName =
    | "ZS_PRODUCT_ID"
    | "THEME_PRIMARY_COLOR"
    | "THEME_BACKGROUND_COLOR"
    | "THEME_LIGHT_MODE";

export const kcEnvNames: KcEnvName[] = [
    "ZS_PRODUCT_ID",
    "THEME_PRIMARY_COLOR",
    "THEME_BACKGROUND_COLOR",
    "THEME_LIGHT_MODE"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    ZS_PRODUCT_ID: "hypredge",
    THEME_PRIMARY_COLOR: "",
    THEME_BACKGROUND_COLOR: "",
    THEME_LIGHT_MODE: ""
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    | import("./account/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));
export const KcAccountPage = lazy(() => import("./account/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                    case "account":
                        return <KcAccountPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
